version: "3.9"

services:
  client:
    image: rope-client:${TAG:-latest}
    command:
      - -config=/config.json
    volumes: # test monroe config
      - type: bind
        source: ${CLIENT_CONF} # Client configuration
        target: /config.json
        read_only: true
      - type: bind
        source: ${CLIENT_APP} # Application configuration
        target: /appconfig.toml
        read_only: true    
    depends_on:
      - logger
      - proxy

  background:
    image: rope-client:${TAG:-latest}
    privileged: true
    command:
      - -config=/config.json
    volumes: # test monroe config
      - type: bind
        source: ${BACKGROUND_CONF} # Client configuration
        target: /config.json
        read_only: true
      - type: bind
        source: ${BACKGROUND_APP} # Application configuration
        target: /appconfig.toml
        read_only: true    
    depends_on:
      - logger
      - proxy
          
  proxy:
    image: rope-routing:${TAG:-latest}
    command:
      - -sinks=serverlow:4040 servermedium:4040 serverhigh:4040
      - -timeout=30s
      - -listen=0.0.0.0:4040
      - -loggerAddress=logger:8086
      - -loggerToken=${TOKEN}
      - -confFile=/conf.toml
      - -loggerBucket=${BUCKET}
    volumes:
      - type: bind
        source: ${PROXY_CONF}
        target: /conf.toml
        read_only: true 
    ports:
      - "4242:4040/udp"
    depends_on:
      - logger

  serverlow:
    image: rope-server:${TAG:-latest}
    privileged: true
    command:
      - -listen=0.0.0.0:4040
      - -idDevice=serverlow
      - -queueLen=1000000
      - -workers=1
      - -loggerAddress=logger:8086
      - -loggerToken=${TOKEN}
      - -loggerBucket=${BUCKET}
      - -appConfig=/appconfig.toml
    ports:
      - "4343:4040/udp"
    volumes:
      - type: bind
        source: ${SERVERL_APP}
        target: /appconfig.toml
        read_only: true  
    depends_on:
      - logger

  servermedium:
    image: rope-server:${TAG:-latest}
    privileged: true
    command:
      - -listen=0.0.0.0:4040
      - -idDevice=servermedium
      - -queueLen=1000000
      - -workers=1
      - -loggerAddress=logger:8086
      - -loggerToken=${TOKEN}
      - -loggerBucket=${BUCKET}
      - -appConfig=/appconfig.toml
    volumes:
      - type: bind
        source: ${SERVERM_APP}
        target: /appconfig.toml
        read_only: true
    ports:
      - "4444:4040/udp"
    depends_on:
      - logger
      
  serverhigh:
    image: rope-server:${TAG:-latest}
    privileged: true
    command:
      - -listen=0.0.0.0:4040
      - -idDevice=serverhigh
      - -queueLen=1000000
      - -workers=1
      - -loggerAddress=logger:8086
      - -loggerToken=${TOKEN}
      - -loggerBucket=${BUCKET}
      - -appConfig=/appconfig.toml
    volumes:
      - type: bind
        source: ${SERVERH_APP}
        target: /appconfig.toml
        read_only: true
    ports:
      - "4545:4040/udp"
    depends_on:
      - logger

  # First time setup run: docker-compose exec logger influx setup
  logger:
    image: influxdb:alpine
    ports:
      - "8086:8086/tcp"
    volumes:
      - "./influxdbv2:/var/lib/influxdb2"
      - "./:/res"
      - type: bind
        source: ./.env
        target: /.env
        read_only: true
      - type: bind
        source: ./scripts/influx_connect.sh
        target: /influx_connect.sh
        read_only: false
      - type: bind
        source: ./scripts/get_csv.sh
        target: /get_csv.sh
        read_only: false

  sampler:
    image: busybox
    stdin_open: true # docker run -i
    tty: true        # docker run -ts
    
